// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
/* @ts-self-types="./gofmt.d.ts" */
import * as __bridge_wasm from "./gofmt.wasm";
import __bridge_adapter from "./gofmt_binding.js";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

const __bridge_host = __bridge_create_host();
__bridge_wasm._initialize();
const __bridge_api = __bridge_require_api(
	__bridge_adapter.create(__bridge_wasm, __bridge_host),
);
function __bridge_require_api(value) {
	if (value === null || typeof value !== "object") {
		throw new TypeError("formatter adapter create(wasm) must return an object");
	}
	return value;
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") {
		throw new TypeError(`formatter adapter export ${name} must be a function`);
	}
	return value;
}

const __bridge_export_format = __bridge_require_function(__bridge_api.format, "format");
export { __bridge_export_format as format };
