// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
import type * as InitOutput from "./gofmt.wasm";
type InitOutput = typeof InitOutput;

export type SyncInitInput = BufferSource | WebAssembly.Module;

export default function initAsync(): Promise<InitOutput>;
export declare function initSync(input: SyncInitInput): InitOutput;

export * from "./gofmt.d.ts";
