// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
/* @ts-self-types="./gofmt_web.d.ts" */
import __bridge_adapter from "./gofmt_binding.js";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

let __bridge_wasm;
let __bridge_pending;
let __bridge_initializing = false;
let __bridge_binding_format = __bridge_not_initialized;
export { __bridge_binding_format as format };

function __bridge_require_api(value) {
	if (value === null || typeof value !== "object") {
		throw new TypeError("formatter adapter create(wasm) must return an object");
	}
	return value;
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") {
		throw new TypeError(`formatter adapter export ${name} must be a function`);
	}
	return value;
}

function __bridge_not_initialized() {
	throw new Error("WASM module has not been initialized");
}

function __bridge_finalize({ instance, host }) {
	const __bridge_next_wasm = instance.exports;
	__bridge_next_wasm._initialize();
	const __bridge_api = __bridge_require_api(
		__bridge_adapter.create(__bridge_next_wasm, host),
	);
	const __bridge_export_format = __bridge_require_function(__bridge_api.format, "format");
	__bridge_binding_format = __bridge_export_format;
	__bridge_wasm = __bridge_next_wasm;
	return __bridge_wasm;
}

export function initSync(moduleOrBuffer) {
	if (__bridge_wasm !== undefined) return __bridge_wasm;
	if (__bridge_initializing) throw new Error("WASM initialization is already in progress");
	__bridge_initializing = true;
	try {
		const module = moduleOrBuffer instanceof WebAssembly.Module
			? moduleOrBuffer
			: new WebAssembly.Module(moduleOrBuffer);
		const host = __bridge_create_host();
		return __bridge_finalize({ instance: new WebAssembly.Instance(module, host.imports), host });
	} finally {
		__bridge_initializing = false;
	}
}

function __bridge_init_async(load) {
	if (__bridge_wasm !== undefined) return Promise.resolve(__bridge_wasm);
	if (__bridge_pending !== undefined) return __bridge_pending;
	if (__bridge_initializing) return Promise.reject(new Error("WASM initialization is already in progress"));
	__bridge_initializing = true;
	__bridge_pending = Promise.resolve()
		.then(load)
		.then(__bridge_finalize)
		.finally(() => {
			__bridge_pending = undefined;
			__bridge_initializing = false;
		});
	return __bridge_pending;
}

async function __bridge_load(module, imports) {
	if (typeof Response === "function" && module instanceof Response) {
		if (typeof WebAssembly.instantiateStreaming === "function") {
			try {
				return await WebAssembly.instantiateStreaming(module, imports);
			} catch (error) {
				const validResponse =
					module.ok &&
					(module.type === "basic" || module.type === "cors" || module.type === "default");
				const wrongContentType =
					module.headers.get("Content-Type") !== "application/wasm";
				if (validResponse && wrongContentType) {
					console.warn(
						"`WebAssembly.instantiateStreaming` failed because the server did not use the `application/wasm` MIME type. Falling back to `WebAssembly.instantiate`.",
						error,
					);
				} else {
					throw error;
				}
			}
		}
		return WebAssembly.instantiate(await module.arrayBuffer(), imports);
	}

	const result = await WebAssembly.instantiate(module, imports);
	if (result instanceof WebAssembly.Instance) {
		return { instance: result, module };
	}
	return result;
}

export default function initAsync(input) {
	return __bridge_init_async(async () => {
		let resolvedInput = await input;
		if (resolvedInput === undefined) {
			resolvedInput = new URL("gofmt.wasm", import.meta.url);
		}
		if (
			typeof resolvedInput === "string" ||
			(typeof Request === "function" && resolvedInput instanceof Request) ||
			(typeof URL === "function" && resolvedInput instanceof URL)
		) {
			resolvedInput = fetch(resolvedInput);
		}
		const host = __bridge_create_host();
		const { instance } = await __bridge_load(await resolvedInput, host.imports);
		return { instance, host };
	});
}
