// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
/* @ts-self-types="./gofmt_factory.d.ts" */
import __bridge_adapter from "./gofmt_binding.js";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

export function createFormatter(moduleOrBuffer) {
	const __bridge_module = moduleOrBuffer instanceof WebAssembly.Module
		? moduleOrBuffer
		: new WebAssembly.Module(moduleOrBuffer);
	const __bridge_host = __bridge_create_host();
	const __bridge_wasm = new WebAssembly.Instance(__bridge_module, __bridge_host.imports).exports;
	__bridge_wasm._initialize();
	const __bridge_api = __bridge_adapter.create(__bridge_wasm, __bridge_host);
	if (__bridge_api === null || typeof __bridge_api !== "object") {
		throw new TypeError("formatter adapter create(wasm, host) must return an object");
	}
	return {
		["format"]: __bridge_require_function(__bridge_api["format"], "format"),
	};
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") throw new TypeError(`formatter adapter export ${name} must be a function`);
	return value;
}
