// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
/* @ts-self-types="./gofmt_vite.d.ts" */
import __bridge_init from "./gofmt.wasm?init";
import __bridge_adapter from "./gofmt_binding.js";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

let __bridge_wasm;
let __bridge_pending;
let __bridge_initializing = false;
let __bridge_binding_format = __bridge_not_initialized;
export { __bridge_binding_format as format };

function __bridge_require_api(value) {
	if (value === null || typeof value !== "object") {
		throw new TypeError("formatter adapter create(wasm) must return an object");
	}
	return value;
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") {
		throw new TypeError(`formatter adapter export ${name} must be a function`);
	}
	return value;
}

function __bridge_not_initialized() {
	throw new Error("WASM module has not been initialized");
}

function __bridge_finalize({ instance, host }) {
	const __bridge_next_wasm = instance.exports;
	__bridge_next_wasm._initialize();
	const __bridge_api = __bridge_require_api(
		__bridge_adapter.create(__bridge_next_wasm, host),
	);
	const __bridge_export_format = __bridge_require_function(__bridge_api.format, "format");
	__bridge_binding_format = __bridge_export_format;
	__bridge_wasm = __bridge_next_wasm;
	return __bridge_wasm;
}

export function initSync(moduleOrBuffer) {
	if (__bridge_wasm !== undefined) return __bridge_wasm;
	if (__bridge_initializing) throw new Error("WASM initialization is already in progress");
	__bridge_initializing = true;
	try {
		const module = moduleOrBuffer instanceof WebAssembly.Module
			? moduleOrBuffer
			: new WebAssembly.Module(moduleOrBuffer);
		const host = __bridge_create_host();
		return __bridge_finalize({ instance: new WebAssembly.Instance(module, host.imports), host });
	} finally {
		__bridge_initializing = false;
	}
}

function __bridge_init_async(load) {
	if (__bridge_wasm !== undefined) return Promise.resolve(__bridge_wasm);
	if (__bridge_pending !== undefined) return __bridge_pending;
	if (__bridge_initializing) return Promise.reject(new Error("WASM initialization is already in progress"));
	__bridge_initializing = true;
	__bridge_pending = Promise.resolve()
		.then(load)
		.then(__bridge_finalize)
		.finally(() => {
			__bridge_pending = undefined;
			__bridge_initializing = false;
		});
	return __bridge_pending;
}

export default function initAsync() {
	if (arguments.length !== 0) {
		return Promise.reject(new TypeError("Vite initAsync takes no arguments; use the Web entry point for custom inputs"));
	}
	return __bridge_init_async(async () => {
		const host = __bridge_create_host();
		const instance = await __bridge_init(host.imports);
		return { instance, host };
	});
}
