// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
import type * as Formatter from "./gofmt.d.ts";

/** Create an independent formatter, including fresh memory and configuration handles. */
export declare function createFormatter(input: BufferSource | WebAssembly.Module): Pick<typeof Formatter, "format">;
