// Generated by @wasm-fmt/bindgen. Do not edit this file directly.
export declare const memory: WebAssembly.Memory;
export declare function _initialize(): void;
export declare function wasm_fmt_abi_version(): number;
export declare function wasm_fmt_alloc(size: number): number;
export declare function wasm_fmt_reset(): void;
export declare function wasm_fmt_register_config(id: number, ptr: number, len: number): 1 | 3;
export declare function wasm_fmt_release_config(id: number): void;
export declare function wasm_fmt_format(ptr: number, len: number): 0 | 1 | 2 | 3;
export declare function wasm_fmt_output(): number;
export declare function wasm_fmt_error(): number;
